# Generated by Django 3.2.7 on 2021-09-26 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('REVoti', '0002_auto_20210926_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REVoti.subjects'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
