# Generated by Django 3.2.7 on 2021-09-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REVoti', '0003_auto_20210926_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='grade',
            field=models.FloatField(),
        ),
    ]
